# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

# distanceDF <- function() {
#     .Call(`_SpatialKWD_distanceDF`)
# }

compareOneToOne <- function() {
    .Call(`_SpatialKWD_compareOneToOne`)
}

compareOneToMany <- function() {
    .Call(`_SpatialKWD_compareOneToMany`)
}

compareAll <- function() {
    .Call(`_SpatialKWD_compareAll`)
}
